image: docker:latest
stages:
  - lint
  - build
  - test

variables:
  VERSION: 0.1.0
  CI_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

clang_format:
  stage: lint
  image: registry.web.boeing.com/robotics/continuous_integration/clang_format
  script:
    - run_clang_format.sh
  tags:
    - docker-executor
    - linux
    - docker

build:
  stage: build
  image: sres.web.boeing.com:5000/docker:latest
  before_script:
    - echo ${SRES_API_KEY} | docker login ${SRES_REGISTRY} --username ${SRES_USERNAME} --password-stdin
  script:
    - docker build -t ${CI_IMAGE}-${VERSION}  --build-arg http_proxy=http://172.17.0.1:3128 --build-arg https_proxy=http://172.17.0.1:3128 --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg SRES_USERNAME=${SRES_USERNAME} --build-arg SRES_API_KEY=${SRES_API_KEY} .
  tags:
    - docker-executor
    - linux
    - docker

test:
  stage: test
  image: ${CI_IMAGE}-${VERSION}
  variables:
    GIT_STRATEGY: none
  before_script:
    - cd /root/cartographer/build
  script:
    - ./cartographer.common.blocking_queue_test
    - ./cartographer.common.configuration_files_test
    - ./cartographer.common.fixed_ratio_sampler_test
    - ./cartographer.common.lockless_queue_test
    - ./cartographer.common.lua_parameter_dictionary_test
    - ./cartographer.common.math_test
    - ./cartographer.common.rate_timer_test
    - ./cartographer.common.task_test
    - ./cartographer.common.thread_pool_test
    - ./cartographer.io.fake_file_writer_test
    - ./cartographer.io.internal.in_memory_proto_stream_test
    - ./cartographer.io.points_processor_pipeline_builder_test
    - ./cartographer.io.probability_grid_points_processor_test
    - ./cartographer.io.proto_stream_deserializer_test
    - ./cartographer.io.proto_stream_test
    - ./cartographer.mapping.2d.map_limits_test
    - ./cartographer.mapping.2d.probability_grid_test
    - ./cartographer.mapping.2d.range_data_inserter_2d_test
    - ./cartographer.mapping.2d.submap_2d_test
    - ./cartographer.mapping.2d.tsdf_2d_test
    - ./cartographer.mapping.2d.tsdf_range_data_inserter_2d_test
    - ./cartographer.mapping.2d.tsd_value_converter_test
    - ./cartographer.mapping.2d.xy_index_test
    - ./cartographer.mapping.hybrid_grid_test
    - ./cartographer.mapping.id_test
    - ./cartographer.mapping.internal.2d.normal_estimation_2d_test
    - ./cartographer.mapping.internal.2d.overlapping_submaps_trimmer_2d_test
    - ./cartographer.mapping.internal.2d.pose_graph_2d_test
    - ./cartographer.mapping.internal.2d.ray_to_pixel_mask_test
    - ./cartographer.mapping.internal.2d.scan_features.circle_detector_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.ceres_scan_matcher_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.correlative_scan_matcher_test
    - ./cartographer.mapping.internal.2d.scan_matching.fast_correlative_scan_matcher_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.global_icp_scan_matcher_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.icp_scan_matcher_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.interpolated_tsdf_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.occupied_space_cost_function_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.real_time_correlative_scan_matcher_2d_test
    - ./cartographer.mapping.internal.2d.scan_matching.tsdf_match_cost_function_2d_test
    - ./cartographer.mapping.internal.connected_components_test
    - ./cartographer.mapping.internal.motion_filter_test
    - ./cartographer.mapping.internal.optimization.cost_functions.landmark_cost_function_2d_test
    - ./cartographer.mapping.internal.optimization.cost_functions.spa_cost_function_2d_test
    - ./cartographer.mapping.internal.range_data_collator_test
    - ./cartographer.mapping.internal.trajectory_connectivity_state_test
#   - ./cartographer.mapping.map_builder_test  # Currently failing
    - ./cartographer.mapping.pose_extrapolator_test
    - ./cartographer.mapping.pose_graph_test
    - ./cartographer.mapping.pose_graph_trimmer_test
    - ./cartographer.mapping.probability_values_test
    - ./cartographer.mapping.submaps_test
    - ./cartographer.mapping.trajectory_node_test
    - ./cartographer.mapping.value_conversion_tables_test
    - ./cartographer.sensor.compressed_point_cloud_test
    - ./cartographer.sensor.internal.collator_test
    - ./cartographer.sensor.internal.ordered_multi_queue_test
    - ./cartographer.sensor.internal.trajectory_collator_test
    - ./cartographer.sensor.internal.voxel_filter_test
    - ./cartographer.sensor.landmark_data_test
    - ./cartographer.sensor.map_by_time_test
    - ./cartographer.sensor.point_cloud_test
    - ./cartographer.sensor.range_data_test
    - ./cartographer.transform.rigid_transform_test
    - ./cartographer.transform.timestamped_transform_test
    - ./cartographer.transform.transform_interpolation_buffer_test
    - ./cartographer.transform.transform_test
  tags:
    - docker-executor
    - linux
    - docker
