image: docker:latest
stages:
  - lint
  - build

variables:
  VERSION: 0.1.0
  CI_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

clang_format:
  stage: lint
  image: registry.web.boeing.com/robotics/continuous_integration/clang_format
  script:
    - run_clang_format.sh
  tags:
    - docker-executor
    - linux
    - docker

build:
  stage: build
  image: docker:latest
  before_script:
    - cd ros
  script:
    - docker build -t ${CI_IMAGE}-${VERSION}  --build-arg http_proxy=http://172.17.0.1:3128 --build-arg https_proxy=http://172.17.0.1:3128 --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg SRES_USERNAME=${SRES_USERNAME} --build-arg SRES_API_KEY=${SRES_API_KEY} .
  tags:
    - docker-executor
    - linux
    - docker
